package br.com.pagamentos.doubledispatchpattern;

public enum PropriedadesRecibo {
	TRANSACAO, DATA, HORA, BENEFICIARIO, CPF_BENEFICIARIO, CNPJ_BENEFICIARIO, CPF_PAGADOR, CNPJ_PAGADOR, DESCRICAO, VENCIMENTO, VALOR_NOMINAL, METODO_PAGAMENTO, COD_BARRAS, COD_AUTENTICACAO;
}
