package br.com.pagamentos.doubledispatchpattern;

public enum PropriedadesRecibo {
	TRANSACAO, DATA, HORA, BENEFICIARIO, PAGADOR, DESCRICAO, VENCIMENTO, VALOR, METODO_PAGAMENTO, COD_BARRAS, COD_AUTENTICACAO, OPERADORA, CELULAR;
}
